server:
  port: 81

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/



logging:
  level:
    # feign日志以 debug 级别监控 com.zhouxk.springcloud.service.PaymentFeignService 接口
    com.zhouxk.springcloud.service.PaymentHystrixService: debug

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。


#TODO 注意注意注意：feign的超时时间和hystrix的熔断超时时间必须都配置，不然在使用feign调用服务并且开启hystrix时，一直报timeout
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下, 两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000